"""empty message

Revision ID: 12162674db23
Revises: a4e54e79aba6
Create Date: 2022-09-19 13:38:08.066677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12162674db23'
down_revision = 'a4e54e79aba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country')
    op.drop_table('state')
    op.drop_table('cities')
    op.drop_constraint('user_profile_state_fkey', 'user_profile', type_='foreignkey')
    op.drop_constraint('user_profile_country_fkey', 'user_profile', type_='foreignkey')
    op.drop_constraint('user_profile_city_fkey', 'user_profile', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_profile_city_fkey', 'user_profile', 'cities', ['city'], ['id'])
    op.create_foreign_key('user_profile_country_fkey', 'user_profile', 'country', ['country'], ['id'])
    op.create_foreign_key('user_profile_state_fkey', 'user_profile', 'state', ['state'], ['id'])
    op.create_table('cities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('state_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], name='cities_state_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cities_pkey')
    )
    op.create_table('state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='state_country_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='state_pkey')
    )
    op.create_table('country',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='country_pkey')
    )
    # ### end Alembic commands ###
