"""empty message

Revision ID: a4e54e79aba6
Revises: d3c95a8e3ec6
Create Date: 2022-09-14 22:20:12.058995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e54e79aba6'
down_revision = 'd3c95a8e3ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('level_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'classes', 'school_levels', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_column('classes', 'level_id')
    # ### end Alembic commands ###
