"""empty message

Revision ID: e6e5f30624a4
Revises: 8ba8e09ccbd1
Create Date: 2022-09-09 10:01:22.309104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6e5f30624a4'
down_revision = '8ba8e09ccbd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buss_attendance', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('buss_subscription', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cash_report', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('classes', 'deleted_at')
    op.add_column('employee_payment', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('employee_salary', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('marks_evaluation', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('parent_add_student_school', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('parent_follow_up_chat', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('student_address', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('student_level', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('student_parent', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('student_payment', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('students', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('teacher_class', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('teacher_modules', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'birth_date',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birth_date',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('teacher_modules', 'updated_at')
    op.drop_column('teacher_class', 'updated_at')
    op.drop_column('students', 'updated_at')
    op.drop_column('student_payment', 'updated_at')
    op.drop_column('student_parent', 'updated_at')
    op.drop_column('student_level', 'updated_at')
    op.drop_column('student_address', 'updated_at')
    op.drop_column('parent_follow_up_chat', 'updated_at')
    op.drop_column('parent_add_student_school', 'updated_at')
    op.drop_column('marks_evaluation', 'updated_at')
    op.drop_column('employee_salary', 'updated_at')
    op.drop_column('employee_payment', 'updated_at')
    op.add_column('classes', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('cash_report', 'updated_at')
    op.drop_column('buss_subscription', 'updated_at')
    op.drop_column('buss_attendance', 'updated_at')
    # ### end Alembic commands ###
